### ISSUE TITLE
Y-Gantry CAD and github page shows wrong pulley order

### ISSUE THREAD

**Issue by Arakon** [VzBoT3D/VzBoT-Vz330#35]
According to both the CAD and the [images here](https://github.com/VzBoT3D/VzBoT-Vz330/tree/master/Assemblies%20BOM%20and%20STL/Gantry/Y%20gantry/Printed%20Y%20Gantry), the pulleys are supposed to be one toothed, one smooth on each front and back.
However, the actual order to follow the belt orientation should be both toothed in front, both smooth in back.

**Comment by simonvez** [comment]
Thanks! I have checked and the CAD is fine.. its jut the picture was mirrored. I will update the picture. thanks
![image](https://user-images.githubusercontent.com/37383368/172399724-307a91e0-f14a-427e-8a20-654e659ffcdb.png)

**Comment by simonvez** [comment]
Fixed the pictures

**Comment by Arakon** [comment]
Sorry to say, but it's [still wrong](https://github.com/VzBoT3D/VzBoT-Vz330/tree/master/Assemblies%20BOM%20and%20STL/Gantry/Y%20gantry/Printed%20Y%20Gantry).. now the right pulley is shown, but the front pulleys are shown as being in the upper position, when one should be in the lower position, same for the back ones.

**Comment by simonvez** [comment]
I need to stop sniffing glue apparently haha.. ok now its fixed
